name: Eventos
on:
  workflow_dispatch:
  schedule:
      - cron:  '* * 1 * *'
  pull_request:
    branches:
      - main
      - 'release/**'
    types:
      - opened
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  repository_dispatch: 
    types: [mievento]
  
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola mundo
      run: echo "¡Hola Mundo!"