name: 03a - use checkout action
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Run a multi-line script
        run: |
          echo "Hola mundo"
          cat readme.md
