name: 05a - Expresiones
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  expresiones:
    runs-on: ubuntu-latest
    env:
      frutas: |
        [
          { "name": "manzana", "cantidad": 1 },
          { "name": "naranja", "cantidad": 2 },
          { "name": "pera", "cantidad": 1 }
        ]
    steps:
      - name: Operadores
        run: echo "${{ 2 > 1 }}"
      - name: Verificar context
        run: echo "${{ toJSON(github) }}"
      - name: Evento y actor
        run: |
         echo "Evento disparador: ${{ github.event_name }}"
         echo "Lanzado por: ${{ github.actor }}"
      # - name: Filtro de objeto
      #   run: echo "${{ fromJson(env.frutas.*.name) }}"
      # - name: Filtro de objeto
      #   run: echo "${{ join(toJson(env.frutas).*.name, ',') }}"
      - name: Filtro de objeto
        run: echo "${{ join(env.frutas.*.name, ',') }}"
