name: 05a - Expresiones
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  expresiones:
    runs-on: ubuntu-latest
    env:
      frutas: |
        [
          { "name": "apple", "quantity": 1 },
          { "name": "orange", "quantity": 2 },
          { "name": "pear", "quantity": 1 }
        ]
    steps:
      - name: Operadores
        run: echo "${{ 2 > 1 }}"
      - name: Verificar context
        run: echo "${{ toJSON(github) }}"
      - name: Evento y actor
        run: |
         echo "Evento disparador: ${{ github.event_name }}"
         echo "Lanzado por: ${{ github.actor }}"
      - name: Filtro de objeto
        run: echo "${{ toJson(env.frutas.*.name) }}"
