name: 05b - Información del runner
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar OS y arquitectura
        run: |
         echo "Sistema operativo: ${{ runner.os }}"
         echo "Arquitectura del sistema: ${{ runner.arch }}"
