name: 06b - Pasar valores entre steps
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generar número aleatorio
        run: echo "NUM_ALEATORIO=$((1 + RANDOM % 6))" >> "$GITHUB_ENV"
      - name: Escribir Resumen
        run: |
         echo "# :game_die: El resultado es:" >> $GITHUB_STEP_SUMMARY
         echo ${{env.NUM_ALEATORIO}} >> $GITHUB_STEP_SUMMARY
