name: 10a - entornos
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  entornos:
    permissions: 
      contents: read
    runs-on: ubuntu-latest
    environment: prod
    env:
      # GH_TOKEN: ${{ github.token }}
      GH_TOKEN: ${{ secrets.APP_TOKEN }}
    steps:
      - name: Verificar variable
        run: echo "${{vars.UNA_VARIABLE}}"
      - name: Verificar secreto
        run: echo "${{secrets.UN_SECRETO}}"
      - name: Leer repos
        run: gh auth login --with-token ${{ secrets.APP_TOKEN }} && gh repo list
