name: 10a - entornos
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  entornos:
    runs-on: ubuntu-latest
    environment: prod
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Verificar variable
        run: echo "${{vars.UNA_VARIABLE}}"
      - name: Verificar secreto
        run: echo "${{secrets.UN_SECRETO}}"
      - name: Leer repos
        run: gh repo list
