name: 10a - entornos
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  entornos:
    # permissions: 
    #   contents: read
    permissions: {}
    runs-on: ubuntu-latest
    environment: prod
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Verificar variable
        run: echo "${{vars.UNA_VARIABLE}}"
      - name: Verificar secreto
        run: echo "${{secrets.UN_SECRETO}}"
      - name: Leer repos 1
        run: gh repo list
      - name: Leer contenido
        run: gh repo view ${{ github.repository }}
      - name: Listar issues
        run: issue list --state all
      # - name: Generar token
      #   id: app-token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.PRIVATE_KEY }}
      #     owner: juancho85
      # - name: Leer repos 2
      #   env:
      #     GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      #   run: gh repo list
