name: 12b - Ejercicio de workflow reutilizable
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  uso-compuesto:
    runs-on: ubuntu-latest
    name: Job para probar jobs compuestos
    steps:
      - id: compuesta
        uses: juancho85/gha-composite-action@v1
        with:
          numero-dados: 'uno'
      - run: echo dado 1 es ${{steps.compuesta.outputs.dado1}} 