name: 12a - Ejemplo de workflow reutilizable
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Use local hello-world-action
        uses: ./.github/actions/hello-world-action