name: 12b - Ejercicio de workflow reutilizable
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/12a-npm-build-llamado.yml
    with:
      versiones-node: "['20']"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: despliegue
        run: echo "Desplegando en AWS..." 
