name: 14a - Ejemplo docker saluda
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  uso-compuesto:
    runs-on: ubuntu-latest
    name: Uso acción docker python
    steps:
      - id: javascript
        uses: juancho85/gha-dockerpy-hola@v1
        with:
          nombre: 'Juan'
      - name: El saludo
        run: echo "${{steps.javascript.outputs.saludo}}"