name: 15b - Github token
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  issues: read
# permissions: {}
jobs:
  test-permissions:
    name: Test permissions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cat .git/config
    - name: Retrieve issues via github cli
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh issue list
    - name: Retrieve issues via HTTP
      shell: bash
      run: |
        curl https://api.github.com/repos/${{ github.repository }}/issues \
        -H 'authorization: Bearer ${{ github.token }}' \
        -H 'content-type: application/json'
