name: 15b - Github token
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions: 
    contents: none
jobs:
  permisos:
    name: Prueba permisos
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: cat readme.md
