name: 15b - Github token
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions: {}
jobs:
  permisos:
    name: Prueba permisos
    runs-on: ubuntu-latest
    steps:
    - run: gh issue list
