name: 15b - Github token
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions: {}
jobs:
  permisos:
    name: Prueba permisos
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: juancho85/gha-list-issues@v1
    # - uses: actions/checkout@v4
    # - name: Prueba con GH-CLI
    #   run: gh issue list
    # - name: Prueba con llamada HTTP
    #   run: |
    #     curl https://api.github.com/repos/${{ github.repository }}/issues \
    #     -H 'authorization: Bearer ${{ github.token }}' \
    #     -H 'content-type: application/json'
