name: 15c - Otros repositorios
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  listar-repos:
    name: Test permissions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: listar repos
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh repo list